name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 20 * * 0"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}        
          
          # Options
          user: nhat191024
          template: classic
          config_timezone: Asia/Ha_Noi

          plugin_anilist: yes
          plugin_anilist_user: khoa301020
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, reading, characters
          plugin_anilist_limit: 1
          
          plugin_traffic: yes